modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Rearth/Oritech/issues"
license = "CC0-1.0"

[[mods]]
modId = "oritech"
version = "${version}"
displayName = "Oritech"
authors = "Me! - Rearth"
description = '''
Simple tech mod.
'''
#logoFile = ""

[[dependencies.oritech]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oritech]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oritech]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oritech]]
modId = "athena"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oritech]]
modId = "fabric_api"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oritech]]
modId = "owo"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oritech]]
modId = "geckolib"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "oritech_forge.mixins.json"
